### ISSUE TITLE
Wasm GC in JavaScriptCore

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#12]
## Logistics

* Facilitator: @bashor (JetBrains)
* Date & Time: [Tuesday 6th at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230606T1000)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-Wasm-GC-JavaScriptCore

## Description

- Overview of JSC internals.
- Overview Wasm GC (and related proposal) implementation details.
- Try to build together JSC and fix something simple, preferably around Wasm GC.

## Agenda

TBD

**Comment by bashor** [comment]
The general idea is to help non-experienced devs in JavaScriptCore (JSC), like me😊, to dive into the topic and try to fix the first wasm issue in JSC.

More experienced folks are also super welcome! 
You can start your hackathon earlier while others are exploring JSC internals. 
Or help others with their diving into JSC.

Agenda:
* Overview of Wasm implementation in JSC. (@dbezhetskov)
* Try to fix something simple, preferably around Wasm GC. (All together or in groups, or individually)
   * Make sure everyone built JSC in advance.
--

Preparation:
Since we are limited in time, ask participants to do a few things in advance:
* Read or watch materials about Wasm GC to become familiar.
  * TODO: collect materials.
* Check out and build JSC
  * TODO: instruction, likely instruction inside WebKit repo is enough.
* Something to read about JSC internals? (Nice to have)
* Prepare a list of simple issues to look at during the session, preferably around Wasm GC
--

(will be updated)

**Comment by bashor** [comment]
Special Thanks:
* @dbezhetskov who kindly agreed to make an overview!
* @catamorphism for valuable comments and recommendations!
* @chicoxyzzy volunteered to help during the session!

**Comment by bashor** [comment]
Please Join [WebKit](https://webkit.slack.com/) Slack workspace. [Link](https://join.slack.com/t/webkit/shared_invite/zt-c7ze4vec-eW_usHwX7IXHEvDZ2FN5lA) to join.

Drop the message here https://webkit.slack.com/archives/CTV4FGWF4/p1686043667584729 so I add you to the private channel.

**Comment by spectranaut** [comment]
Notes (if necessary): https://notes.igalia.com/YbGF7z3eQ86Cf7Prz-kWnA#

**Comment by bashor** [comment]
### Checkout 
`git clone -b main --single-branch --depth=1 https://github.com/WebKit/WebKit`

### Build
`./Tools/Scripts/build-jsc --jsc-only --debug`

If it fails, try:
`./Tools/Scripts/build-jsc --debug`

### Run wasm GC tests
`./Tools/Scripts/run-javascriptcore-tests --no-testapi --no-build --no-fail-fast --debug --jsc-only --filter wasm/gc/`

**Comment by bashor** [comment]
[WasmGC: Minimal JavaScript Interop:](https://docs.google.com/document/d/17hCQXOyeSgogpJ0I0wir4LRmdvu4l7Oca6e1NkbVN8M/edit#heading=h.jnkwn2nuqgbi)

>**Wasm objects in JS appear opaque**
Wasm structs and arrays will appear on the JavaScript side as frozen empty objects, i.e. having no properties, and it's not possible to add any. Attempting to write a property throws a TypeError. 
Formally: their [[Set]], [[DefineOwnProperty]], [[Delete]] internal slots throw exceptions (regardless of strict mode). [[HasProperty]] and [[IsExtensible]] return false. [[Get]] and [[GetOwnProperty]] return undefined. [[OwnPropertyKeys]] returns an empty list.

**Comment by dbezhetskov** [comment]
test scripts: WebKitBuild/Debug/bin/jsc-stress-results/.runner
